  
language: go

# Force-enable Go modules. Also force go to use the code in vendor/
# These will both be unnecessary when Go 1.14 lands.
env: GO111MODULE=on

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.15.x
git:
  depth: 1

services:
  - docker
install: true


jobs:
  include:
    - stage: test
      before_script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2
      script:
        - go test -race -coverprofile c.out ./...
        - golangci-lint run
    - name: Dockerhub Deploy
      if: tag IS present
      stage: deploy
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - docker build . -t samtholiya/analyser-service:$(git describe --tags)
        - docker build . -t samtholiya/analyser-service:latest
        - docker push samtholiya/analyser-service:$(git describe --tags)
        - docker push samtholiya/analyser-service:latest
